categories:
  - travel
  - training
  - talks
  - featured

gems:
  - jekyll-archives
  
permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

collections:
   workouts:
      output: true
